### ISSUE TITLE
Checking for CLS Compliance

### ISSUE THREAD

**Issue by willsb** [fsprojects/FSharpLint#124]
[This MSDN page](https://msdn.microsoft.com/en-us/library/vstudio/bhc3fa7f(v=vs.100).aspx) states  that compilers may check during build-time if classes/methods annotated with the `CLSCompliantAttribute` are indeed CLS compliant and emit a warning if they're not. Currently the C# and VB.net compilers do this checking, but fsc doesn't. 

I opened an issue on the fsharp language repository to get this implemented there, but I was told it wasn't relevant enough to enter the core compiler. They recommended this project as a possible place where the feature could be implemented.

The question is: Is it interesting to have such check here on FSharpLint?
If the answer is yes, I'm willing to start working on it :)

**Comment by duckmatt** [comment]
Hi, this does sound like a good idea. Have you tried running FxCop on an F# assembly? I think that might possibly get you warning for non-CLS compliant code. But it would be great to have a new analyser in the linter to find non-CLS compliant code that's marked as CLS compliant

**Comment by willsb** [comment]
Good to hear!
I'll start working on it ASAP and let you know of the progress :)

**Comment by duckmatt** [comment]
Okay great, let me know if you run into any difficulties. One that may crop up is currently the files are analysed on a per file basis, but in your case you'll probably want to know if there's an `CLSCompliantAttribute` in the `AssemblyInfo` file while analysing all other files in a project. This will probably need the `Framework` project updated so that visitors can access the attributes in `AssemblyInfo`

**Comment by duckmatt** [comment]
How's this going? If it hasn't been started I think it would probably be worth doing as its own project
