### ISSUE TITLE
Direction of the linter

### ISSUE THREAD

**Issue by duckmatt** [fsprojects/FSharpLint#144]
# Direction

At the moment attempting to maintain this while developing new features has become too difficult for the amount of time I have, and the size of the project has made it difficult others to contribute. I'm planning to do a significant rewrite of the core of the linter as well as moving projects that aren't integral to the linter (MSBuild task and FAKE task) to their own repositories.

The new direction will be based around pattern matching against the AST to find patterns in the code that could possibly be refactored. *"Code review"* rules e.g. functions must be a certain pre-described length will no longer fit in this direction of the project. The F# community is very pragmatic so from what I've heard from others these rules don't really fit the community either.

#### Goals

* Faster analysis
* Partial analysis - *if a small part of the AST has changed we shouldn't need to analyse the entire AST again*
* Reduced set of more useful rules
* Smaller code base
* Less focus on style based rules; more focus on behaviour/performance/simplifying based rules
* Easier for others to contribute
* Refactoring API
* Less dogmatic - *ensure people are aware these are possible suggestions not errors*

##### Rules To Keep

* Naming
* Lambda length
* Number of items in a tuple pattern - *this may eventually be a hint*
* Binding to wildcard - *this will eventually be a hint*
* RaiseWithTooManyArguments - *until fixed in the F# compiler*
* Documentation - *off by default*
* Eta reduction suggestion
* User defined hints
* *More pattern based rules in the future e.g. suggest `List.map` in place of an equivalent function that maps a list via recursion*

##### Rules To Remove

* SourceLength - *other than lambda*
* NumberOfItems - *other than tuple*
* CyclomaticComplexity
* Typography - *Possibly staying; if so would be off by default*
* NestedStatements

#### Please comment on the direction you'd like to see the tool take

**Comment by isaacabraham** [comment]
Having not looked at the codebase in any depth, I can't comment on the internal redesigns your proposing. But from a user point-of-view, I can't speak highly enough of this tool. Ironically one of the lints that I never pay attention to is the lambda length rule :-) Typography I would like to keep as I hate having trailing spaces on lines and lint shows these up nicely.

When I think about lint from an educational / learning tool, more powerful analysis lints are where I would love to see more in future e.g. things like CanBeReplacedWithComposition are great.

**Comment by ploeh** [comment]
Like @isaacabraham, I'm quite happy with the linter as a user, but I wouldn't mind being able to suppress specific warnings. Most of the times, the warnings are reasonable, but occasionally, there are reasons to do things differently than the linter wants. It'd be nice to be able to go: *yes, I've already seen this warning, but in this particular case, I think it's a false positive, so please don't show it again*.

Apart from false positives, other reasons for suppressing a warning could be that the proposed change would be a breaking change in an already published API.

**Comment by xavierzwirtz** [comment]
If you could have the linter support selective disabling warnings via a comment, the linter could let you auto insert that comment from an action on the warning.

**Comment by isaacabraham** [comment]
@ploeh You can disable specific lint warnings through FSharpPowerTools, so I imagine that you can do the same with FSharpLint directly via configuration?

It would be nice to be able to configure lints e.g. lambdas more than n lines rather than just "more than 8 lines" etc.

I'm not a fan of disabling of warnings via comments - I find it pollutes my code, personally I would prefer to keep the two separate.

**Comment by ploeh** [comment]
@isaacabraham I know that I can disable certain rules, but that's not my point. I want to be able to dismiss specific warnings. Let me share an example.

When implementing an MVC Web API in F#, I have to define a method called `Application_Start` in a class called `Global`. The linter complains about the underscore.

In general I agree that methods and functions shouldn't have underscores in their names, but in this particular case, I can't do anything about it, because the method is used by convention. If I rename it, my application will no longer work.

Still, I'd like the lint rule to still be in effect, but I don't want to see the warning concerning `Application_Start`.

**Comment by isaacabraham** [comment]
@ploeh that makes sense. With code analysis, you could either put a #directive above the code to disable - personally I don't like this as it pollutes the code - or you had a single file where all your "disable here" bits went.

**Comment by dungpa** [comment]
Writing a linter is hard. You can't please everyone.

#### Add/remove rules

I don't think you should remove existing rules. It's better to have a less ambitious set of default rules, that suits pragmatic styles of F# programmers.

#### Target audience

For the future, I would like to see FSharpLint tailor to new/immediate F# users. It means that the focus should be on shallow and syntactic suggestions that help write better F# code. There is a space for a deep analysis tool for F# but I don't think FSharpLint should do that (and F# tooling infrastructure isn't ready for it either.)

#### FSharpLint as a tool vs a library

With F# addin in Xamarin Studio and FSAutocomplete adding FSharpLint support (see https://github.com/fsharp/xamarin-monodevelop-fsharp-addin/commits/fslint and https://github.com/fsharp/FsAutoComplete/pull/83), FSharpLint are reaching all possible platforms. I see FSharpLint as a library/platform to enable linting on all IDE, editors rather than a standalone tool. That said, it would be great to have a more extensive FSharpLint.Core API. At least, we should have more structured data from linting API to be able to implement quick fixes for rules if possible.

**Comment by isaacabraham** [comment]
@dungpa agree that there is real value for a beginner to F# using this.

**Comment by duckmatt** [comment]
Thanks for all the comments. It's good to hear that on the whole people are finding it a useful tool. 

@isaacabraham it's already possible to [configure the number of lines in a lambda warning](https://github.com/fsprojects/FSharpLint/blob/master/src/FSharpLint.Framework/DefaultConfiguration.FSharpLint#L190) :)

@ploeh the tool supports `SuppressMessageAttribute` unfortunately this doesn't appear to be working in VFPT at the moment so I'll take a look into why that might be.

It's unfortunate there's a case of false positives, with some of the rules e.g. the hints it's very difficult currently to guarantee with any kind of performance (would need to check `List.map` is actually the `List.map` in `FSharp.Core`, check there's no mutation in certain function passed to `List.map` etc). I think a lint level needs to be applied to the warnings generated e.g. naming warnings should be classed as a warning, and hints should be classed as a suggestion. Then editors could choose to display suggestions in a less intrusive way

Keeping these comments in mind it seems like the current direction should be:
	
 * Keep current rules where possible
 * Focus on performance
 * Focus on API to allow for editor refactoring
	
Performance is the current main focus, the hints are causing big issues as they have a runtime 
of `O(n * nh * h)` (n = length of ast, nh = number of hints, h = size of hint) with currently a very simple algorithm, this is where the idea of making the tool mostly work on patterns has been coming from as I've been experimenting with turning the AST into a suffix tree for the hints to be run against, going to require a bit more work before I find out how feasible it's going to be
