### ISSUE TITLE
Linter expects ¯\_(ツ)_/¯ to be camel cased and remove underscores

### ISSUE THREAD

**Issue by raholland79** [fsprojects/FSharpLint#191]
### Description

![image](https://cloud.githubusercontent.com/assets/22954/20323184/57153ade-ab41-11e6-994e-9bdd0c363b18.png)

Linter flags this with the green squiggle in vscode and wants me to camel case and remove underscores.

![image](https://cloud.githubusercontent.com/assets/22954/20323265/90f58434-ab41-11e6-9094-5f7204dfcdb2.png)

I can't figure out how to Camel Case this.

**Comment by duckmatt** [comment]
Hey @raholland79, thanks for the report, as you allude to, the naming convention rules probably shouldn't be checking anything within double backticks :P . I've added a fix and your scenario as a [regression test] (https://github.com/fsprojects/FSharpLint/blob/98026f726b82a2e63618ba19b2bae93c42974811/tests/FSharpLint.Core.Tests/Rules/TestNameConventionRules.fs#L1238). The fix is included in v0.4.12
