### ISSUE TITLE
Include compiled version in GitHub releases.

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [fsprojects/FSharpLint#233]
It'd be nice if we have included compiled version of CLI tool in the GitHub releases. For FAKE/MsBuild/normal code usages all users need to do is reference NuGet package. At the moment, there is no easy way of getting command line tool - users need to build it on their own.

**Comment by duckmatt** [comment]
Would be an improvement to get it on the release pages, the current release process is driven by the release tag being made so may need to change that around sightly. If the binaries are needed by anyone before this issue is resolved, they do get built an artifact on appveyor: https://ci.appveyor.com/project/duckmatt/fsharplint-231/build/artifacts

**Comment by duckmatt** [comment]
Since the move to dotnet core we do now have an executable on nuget https://www.nuget.org/packages/dotnet-fsharplint/
