### ISSUE TITLE
Linter is is complaining on member calls 

### ISSUE THREAD

**Issue by forki** [fsprojects/FSharpLint#297]
Originally reported to ionide please see 
https://github.com/ionide/ionide-vscode-fsharp/issues/996#issuecomment-458205532

**Comment by jgardella** [comment]
Hi @forki.

This is a new rule, `TupleCommaSpacing`, based on the [F# style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-tuples). It is enabled by default because it's part of the official style guide. If you disagree with the rule or it being on by default we can discuss further here.

**Comment by forki** [comment]
Yeah I don't think it's a good idea tbh, but it's far less invasive than the other one I reported and it is not introducing clutter. It's only annoying to reformat perfectly good looking code because we now call one style opinion "official" ;-)

**Comment by jgardella** [comment]
Perhaps instead of "official" I should have said Microsoft :). In any case we need to have some defaults for the linter and the Microsoft style guide made the most sense to me.
