### ISSUE TITLE
Add links to docs for warning

### ISSUE THREAD

**Issue by enricosada** [fsprojects/FSharpLint#362]
### Description

To give users a link with more info for each lint warning, we need the doc url based on linter warning code

### Repro steps

For FSAC in PR https://github.com/fsharp/FsAutoComplete/pull/443/files @baronfel added something like

```fsharp
    let pageForLint (code: string) =
        let codeNumber = code.Substring (2) |> int
        match codeNumber with
        | 1 | 2 | 3 -> Some "http://fsprojects.github.io/FSharpLint/TupleFormatting.html"
        | 4 | 5 | 6 | 7 -> Some "http://fsprojects.github.io/FSharpLint/PatternMatchFormatting.html"
        | 8 | 9 -> Some "http://fsprojects.github.io/FSharpLint/Spacing.html"
        | 10 (* | 11 (not present?) *) | 12 -> Some "http://fsprojects.github.io/FSharpLint/Formatting.html"
        | 13 | 14 | 15 -> Some "http://fsprojects.github.io/FSharpLint/Conventions.html"
        | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 30 | 31 | 32 | 33 -> Some "http://fsprojects.github.io/FSharpLint/SourceLength.html"
        | 34 | 35 -> Some "http://fsprojects.github.io/FSharpLint/FunctionReimplementation.html"
        | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50 -> Some "http://fsprojects.github.io/FSharpLint/NameConventions.html"
        | 51 | 52 | 53 | 54 -> Some "http://fsprojects.github.io/FSharpLint/NumberOfItems.html"
        | 55 | 56 | 57 | 58 -> Some "http://fsprojects.github.io/FSharpLint/Binding.html"
        | 60 | 61 | 62 | 63 | 64 -> Some "http://fsprojects.github.io/FSharpLint/Typography.html"
        | _ -> None
```

Will be nice if that function is already defined in `FSharpLint` or the doc url is additional field in `LintWarning.Warning.Info`

**Comment by jgardella** [comment]
@enricosada @baronfel As of v0.13.2, I updated the documentation so that every rule has its own page determined by its identifier (e.g. http://fsprojects.github.io/FSharpLint/rules/FL0001.html). The identifier is now exposed as part of each suggestion exposed by the call to the linter, so with these two thing you should be able to easily point to the correct documentation page without the need to do any parsing. Let me know how this works, happy to re-open if we need to do more work here.

**Comment by baronfel** [comment]
That's wonderful! I'll make an issue to update our page links to these new per-code pages.
