### ISSUE TITLE
Support for dotnet 6.0

### ISSUE THREAD

**Issue by ethangk** [fsprojects/FSharpLint#519]
### Description

Given the [recent](https://dotnet.microsoft.com/download/dotnet/6.0) release of dotnet 6.0, I've attempted to bump my project to that version. We're running into issues with FSharpLint not supporting dotnet 6.0, from what we can see.

### Repro steps

Bump the dotnet version in the docker container to dotnet 6.0. `dotnet tool restore` works ok, but running:
`dotnet fsharplint lint projectName.fsproj` results in

```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' (x64) was not found.
  - The following frameworks were found:
      6.0.0 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=debian.11-x64
```

This is using the most recent (`0.20.2`) version of FSharpLint.

Thanks!

**Comment by ethangk** [comment]
Thanks for getting back to me so quickly. I've cloned the project locally and added the flag to the `global.json` then built. I'm trying to reference it from my project (by adding the local path as an additional source), so that I can test and it's still not working. I suspect it's using the nuget version instead of this local version. I'm fairly new to the dotnet package world. What's the easiest way to verify this/ force it to use the local version?

**Comment by knocte** [comment]
I think you need to generate a nupkg file and use it locally, but don't remember from the top of my head how to do it (especially taking in account that Paket is being used).

**Comment by Cheroukee** [comment]
My team has the same issue as @ethangk 
I've taken to trying the proposed fix, by building it locally and copying the output folder too a container that runs only net6, without any success. 

After doing some research I fell on this thread :  https://github.com/dotnet/sdk/issues/16427 

Setting this excerpt in the project file for the tool made it run on a 6.x runtime
```
<PropertyGroup>
  <RollForward>Major</RollForward>
</PropertyGroup>
```

From what I observed, doing the change in the `config.json` file only changed the behaviour at build time, where if I ; `rollForward: latestMajor` it will build using 6.x for 5.x, but when trying to launch the tool, it fails with the original error.

I can create a PR with the unique change if you think this is a valid fix. Otherwise we can also upgrade to 6.x / multitarget. What's your view on this ?

**Comment by knocte** [comment]
> without any success.

Thanks for testing this!

> From what I observed, doing the change in the config.json file 

I'm guessing you mean global.json, not config.json.

> I can create a PR with the unique change

Yes please!

>  if you think this is a valid fix

Looks like valid, but if you said you tested it and it works, it must be valid!

> Otherwise we can also upgrade to 6.x / multitarget. What's your view on this ?

TBH I think multi-targetting is a bit messy, I think it's better to avoid it if we can. Ideally we should only support .NETStandard 2.0 (which works for both legacy framework 4.x and .NETCore/.NET5/.NET6), however we're not a library, but a tool :)

**Comment by Cheroukee** [comment]
> I'm guessing you mean global.json, not config.json.
Yes indeed !

Does sound good to me! I'll take care of the PR on monday

**Comment by ethangk** [comment]
Great, thanks for looking at this. I'd planned on taking a look today
