### ISSUE TITLE
Consider renaming to FsLint

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharpLint#91]
Hi @duckmatt, 

I've been looking at the naming of F# tools and packages.  Although this seems like a minor thing, I'm wondering if you would consider a renaming of "FSharpLint" to "FsLint". 

This is because nearly all (non-editor) tooling projects use "FsXyz" naming, e.g. FsLexYacc, FsReveal, FsXaml, FsBlog. In contrast, starting with "FSharp" usually indicates a library, e.g. "FSharp.Core" or "FSharp.Control.AsyncSeq".

I understand it is work to rename but it may be worth it.  Think it over - there's no rush - but consistency can be valuable and brings simplicity and regularity to the ecosystem. 

Best regards
Don

**Comment by duckmatt** [comment]
Hi Don, I agree. I preferred "FsLint" and when I first started that's what I went with, the reason I ended up changing it is that there is an existing [linux tool with the same name](http://www.linuxjournal.com/content/fslint-annoyingly-vague-useful). I feel since they're different domains that sharing the same name should avoid most confusion but could still cause a little, what do you think?
Thanks, Matt

**Comment by dsyme** [comment]
Oh, I see, I just keep the current name then :) all the best, don
